# Generated by Django 4.0.5 on 2023-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=50)),
                ('Project_Technologies', models.CharField(max_length=200)),
                ('Technical_Skillset_Frontend', models.CharField(max_length=150, null=True)),
                ('Technical_Skillset_Backend', models.CharField(max_length=150, null=True)),
                ('Technical_Skillset_Databases', models.CharField(max_length=150, null=True)),
                ('Technical_Skillset_Infrastructre', models.CharField(max_length=50, null=True)),
                ('Other_Information_Availability', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
